### ISSUE TITLE
下载文件有个地方条件写反了

### ISSUE THREAD

**Issue by Zuozihao** [XueYangLee/CustomNetWorking#2]
第326行左右，判断文件夹存在创建文件夹的条件反了
`   BOOL folderExist = [fileManager fileExistsAtPath:downloadDirectory];
    if (folderExist) {
        [fileManager createDirectoryAtPath:downloadDirectory withIntermediateDirectories:YES attributes:nil error:nil];//创建Download目录
    }`

**Comment by XueYangLee** [comment]
好的
