### ISSUE TITLE
萌新发问，进阶使用方法请教

### ISSUE THREAD

**Issue by myDonghao** [XueYangLee/CustomNetWorking#3]
作者大大请教一下，怎么能不动源码的情况下，根据不同的接口改请求头中的参数啊？
场景：
多语言传语言类型，然后有个特殊接口，就只有中文版和英文版，所以请求头里得判断一下，如果不是中文都传“en”。
目前的处理是直接拉代码改动的。

**Comment by XueYangLee** [comment]
> 作者大大请教一下，怎么能不动源码的情况下，根据不同的接口改请求头中的参数啊？ 场景： 多语言传语言类型，然后有个特殊接口，就只有中文版和英文版，所以请求头里得判断一下，如果不是中文都传“en”。 目前的处理是直接拉代码改动的。

在NetRequestConfig中- (NSMutableDictionary<NSString *,NSString *> *)requestMutableHeader判断下中英文的区别就可以了啊   不清楚的看参数备注

**Comment by myDonghao** [comment]
就一个接口是这样的，其他接口都不变嗯？我想到了，我直接创建额外创建一个config，用的时候切一下，用完再换回来。感谢大佬回复！嘿嘿





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 下午4:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XueYangLee/CustomNetWorking] 萌新发问，进阶使用方法请教 (Issue #3)





  
作者大大请教一下，怎么能不动源码的情况下，根据不同的接口改请求头中的参数啊？ 场景： 多语言传语言类型，然后有个特殊接口，就只有中文版和英文版，所以请求头里得判断一下，如果不是中文都传“en”。 目前的处理是直接拉代码改动的。
  
在NetRequestConfig中- (NSMutableDictionary<NSString *,NSString *&gt; *)requestMutableHeader判断下中英文的区别就可以了啊   不清楚的看参数备注
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by myDonghao** [comment]
config中拿不到借口，无法根据接口来判断，所以之前一直没想到如何处理比较好。
